"""init_tables

Revision ID: 51a8717dc6d9
Revises: d03797d0a89d
Create Date: 2026-07-29 11:21:04.729837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '51a8717dc6d9'
down_revision: Union[str, Sequence[str], None] = 'd03797d0a89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. POSTGRESQL VEKTÖR EKLENTİSİNİ AKTİFLEŞTİRİYORUZ
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    
    # 2. EKSİK OLAN ENUM TİPLERİNİ MANUEL OLARAK YARATIYORUZ
    jobstatus_enum = postgresql.ENUM('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED', name='jobstatus')
    jobstatus_enum.create(op.get_bind(), checkfirst=True)
    
    jobstage_enum = postgresql.ENUM('PENDING', 'FILE_VALIDATION', 'TEXT_EXTRACTION', 'PREPROCESSING', 'CHUNKING', 'EMBEDDING', 'ANALYZING_REQUIREMENTS', 'GENERATING_IDEAS', 'COMPLETED', name='jobstage')
    jobstage_enum.create(op.get_bind(), checkfirst=True)
    
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=False),
    sa.Column('page_end', sa.Integer(), nullable=False),
    sa.Column('section_title', sa.String(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_chunk_id'), 'document_chunks', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('critical_dates', sa.JSON(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['analysis_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_id'), 'analysis_results', ['id'], unique=False)
    op.create_table('project_ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_result_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('suitability_reason', sa.Text(), nullable=False),
    sa.Column('ai_contribution_score', sa.Integer(), nullable=False),
    sa.Column('feasibility_score', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('advantages', sa.JSON(), nullable=True),
    sa.Column('disadvantages', sa.JSON(), nullable=True),
    sa.Column('source_chunk_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_result_id'], ['analysis_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_ideas_id'), 'project_ideas', ['id'], unique=False)
    op.add_column('analysis_jobs', sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED', name='jobstatus'), nullable=False))
    op.add_column('analysis_jobs', sa.Column('stage', sa.Enum('PENDING', 'FILE_VALIDATION', 'TEXT_EXTRACTION', 'PREPROCESSING', 'CHUNKING', 'EMBEDDING', 'ANALYZING_REQUIREMENTS', 'GENERATING_IDEAS', 'COMPLETED', name='jobstage'), nullable=False))
    op.add_column('analysis_jobs', sa.Column('progress_percentage', sa.Integer(), nullable=False))
    op.add_column('analysis_jobs', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('analysis_jobs', sa.Column('started_at', sa.DateTime(), nullable=True))
    op.add_column('analysis_jobs', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.alter_column('analysis_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('analysis_jobs', 'job_status')
    op.drop_column('analysis_jobs', 'job_stage')
    op.drop_column('analysis_jobs', 'updated_at')
    op.add_column('documents', sa.Column('mime_type', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('character_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('extraction_method', sa.String(), nullable=True))
    op.add_column('documents', sa.Column('processing_status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED', name='jobstatus'), nullable=False))
    op.add_column('documents', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('documents', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('documents', 'uploaded_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('documents', 'updated_at')
    op.drop_column('documents', 'created_at')
    op.drop_column('documents', 'processing_status')
    op.drop_column('documents', 'extraction_method')
    op.drop_column('documents', 'character_count')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'mime_type')
    op.add_column('analysis_jobs', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('analysis_jobs', sa.Column('job_stage', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('analysis_jobs', sa.Column('job_status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('analysis_jobs', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('analysis_jobs', 'completed_at')
    op.drop_column('analysis_jobs', 'started_at')
    op.drop_column('analysis_jobs', 'retry_count')
    op.drop_column('analysis_jobs', 'progress_percentage')
    op.drop_column('analysis_jobs', 'stage')
    op.drop_column('analysis_jobs', 'status')
    op.drop_index(op.f('ix_project_ideas_id'), table_name='project_ideas')
    op.drop_table('project_ideas')
    op.drop_index(op.f('ix_analysis_results_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chunk_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    
    # ENUM tiplerini temizle
    postgresql.ENUM(name='jobstatus').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='jobstage').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###