from enum import Enum

class JobStage(str, Enum):
    PENDING = "PENDING"
    FILE_VALIDATION = "FILE_VALIDATION"
    TEXT_EXTRACTION = "TEXT_EXTRACTION"
    PREPROCESSING = "PREPROCESSING"
    CHUNKING = "CHUNKING"
    EMBEDDING = "EMBEDDING"
    ANALYZING_REQUIREMENTS = "ANALYZING_REQUIREMENTS"
    GENERATING_IDEAS = "GENERATING_IDEAS"
    COMPLETED = "COMPLETED"

